spring.application.name=Honey Shop Application

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.hibernate.persister.entity=ERROR

users.default-user.name=Galina
users.default-user.email=galina.k.georgieva@abv.bg
users.default-user.country=BULGARIA

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax