spring.application.name=Honey Shop Application

# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/honney-shop-application?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
logging.level.org.hibernate.persister.entity=ERROR

# User properties
users.default-user.name=Galina
users.default-user.password=${DEFAULT_ADMIN_PASSWORD}
users.default-user.email=galina.k.georgieva@abv.bg
users.default-user.country=BULGARIA
users.test-property=This is my test property

server.servlet.session.cookie.secure=true

review.service.base-url=${REVIEW_SERVICE_BASE_URL}
